[package]
name = "agent"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = { version = "0.8.0", default-features = false }
alloy-trie = { version = "0.5.0", default-features = false }
alloy-rlp = "0.3.8"
t-rust = { path = "../t-rust/" }